[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow_core      = "3BXJUR36foqaXawy5dQCPx1amq5yPzQSfPygjx4GSk3s"
condition_oracle = "3crHL5VNeSDvFgpCYEEMUYCfUhrQHu2KBauAaU9qfbMG"
multisig_guard   = "BweWEmsS5txchdCRTgPLi31UNeS19rf4DpQnTDsubVLY"

[programs.localnet]
escrow_core      = "3BXJUR36foqaXawy5dQCPx1amq5yPzQSfPygjx4GSk3s"
condition_oracle = "3crHL5VNeSDvFgpCYEEMUYCfUhrQHu2KBauAaU9qfbMG"
multisig_guard   = "BweWEmsS5txchdCRTgPLi31UNeS19rf4DpQnTDsubVLY"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet =  "/Users/nakshatravijaythange/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[workspace]
members = [
  "programs/escrow-core",
  "programs/condition-oracle",
  "programs/multisig-guard",
]

[hooks]
